module: Product

port: 9000

database:
  provider: postgres
  url:  postgresql://postgres:l@localhost:3000/newdb1
  models:
    - table: Products
      schema:
        Productid: Int @id
        Name: String 
        Price: Float


kafka: localhost:9092


endpoints: 
  - name: AddProduct
    path: /addproduct/
    method: POST
    table: Products
    kafka:
      topic: orderid
      type: consumer
    json:
        type: object
        properties:
            productid: int 
            name: string
            price: float64

          


  


