apiVersion: v1
kind: Service
metadata:
  name: my-pr-service
spec:
  type: NodePort
  selector:
    app: my-pr-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000

